### ISSUE TITLE
import urllib.parse in publishers.py fails for Python 2 

### ISSUE THREAD

**Issue by rohitkrai03** [shon/appbase#7]

**Comment by shon** [comment]
Rohit check https://github.com/shon/appbase/pull/6

**Comment by shon** [comment]
Rohit check https://github.com/shon/appbase/pull/6


On May 26, 2017 13:55, "Rohit Kumar Rai" <notifications@github.com> wrote:

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/shon/appbase/issues/7>, or mute the thread

**Comment by shon** [comment]
pull#8 fixes it. 

Thanks @rakeshgunduka
